### ISSUE TITLE
Parser accept requests where line ends with only one \n.

### ISSUE THREAD

**Issue by evilsocket** [evilsocket/librestd#3]
qwmbp:~ qwertyoruiop$ cat req.txt | nc 127.0.0.1 8080
    HTTP/1.1 200 Ok
    Content-Type: application/json
    Server: librestd/1.0
    Content-Length: 87
    Connection: close

    {
      "object": {
        "foo": "bar"
      },
      "string": "hello world",
      "time": 1509541679
    }qwmbp:~ qwertyoruiop$ xxd req.txt
    00000000: 4745 5420 2f6a 736f 6e20 4854 5450 2f31  GET /json HTTP/1
    00000010: 2e31 0d0a                                .1..

Tnx to [Luca Todesco](https://twitter.com/qwertyoruiopz/status/925710670368256000) for the feedback.

**Comment by evilsocket** [comment]
The main logic issue with this is that the request is read from the socket [in one whole chunk](https://github.com/evilsocket/librestd/blob/master/src/http_server.cpp#L48) while, in order to handle such cases properly, the buffer should be read line by line until a `\n\n` is found, the headers parsed and the read operation continued if the parser determined there's something else to read ( POSTed data, etc ).

**Comment by kpwn** [comment]
one case where this matters: i'm trying to audit this codebase and using "nc" to manually poke around will trigger the bug :)

**Comment by evilsocket** [comment]
Yes the bug is easily triggerable indeed, I'm just thinking on how to prioritize this. 

I already needed to implement a read line-by-line approach in order to support file uploads ( and generally requests bigger than  `http_request::max_size` value ), but it's low priority compared to other stuff I need to implement, **unless** I find the current logic to be a potential **security** issue, in which case I'd escalate it to top priority.
